/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package quizzer
import kotlinx.cli.*

fun main(args: Array<String>) {
    val parser = ArgParser("example")
    val file by parser.option(ArgType.String, shortName = "f", description = "Question file")
    val questionCount by parser.option(ArgType.Int, shortName = "q", description = "Number of questions to ask")
    parser.parse(args)
    val quiz = Quiz()
    if (file?.isNotEmpty() == true) {
        quiz.createQuestions(file!!)
    }
    if (null != questionCount && questionCount!! > 0) {
        quiz.getQuestions(questionCount)
        quiz.start();
    }
}
